# Generated by Django 3.1 on 2020-08-16 11:16

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='DATE UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='CITY')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='COUNTRY')),
                ('lat', models.FloatField(default=0.0, verbose_name='LATITUDE')),
                ('lng', models.FloatField(default=0.0, verbose_name='LONGITUDE')),
                ('weather_time', models.DateTimeField(blank=True, null=True, verbose_name='WEATHER TIME')),
                ('period_start', models.DateTimeField(blank=True, null=True, verbose_name='START PERIOD')),
                ('period_end', models.DateTimeField(blank=True, null=True, verbose_name='END PERIOD')),
                ('min_temp', models.FloatField(default=0.0, verbose_name='MIN. TEMP')),
                ('max_temp', models.FloatField(default=0.0, verbose_name='MAX. TEMP')),
                ('avg_temp', models.FloatField(default=0.0, verbose_name='AVERAGE. TEMP')),
                ('med_temp', models.FloatField(default=0.0, verbose_name='MEDIAN. TEMP')),
                ('humidity', models.CharField(blank=True, max_length=200, null=True, verbose_name='HUMIDITY')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='DESCRIPTION')),
                ('sunrise', models.CharField(blank=True, max_length=200, null=True, verbose_name='SUNRISE')),
                ('sunset', models.CharField(blank=True, max_length=200, null=True, verbose_name='SUNSET')),
                ('icon', models.CharField(blank=True, max_length=200, null=True, verbose_name='WEATHER ICON')),
            ],
            options={
                'db_table': 'btk_climates',
            },
        ),
    ]
